CREATE TABLE IF NOT EXISTS urls (
    id serial PRIMARY KEY,
    origin_url VARCHAR  UNIQUE NOT NULL,
    hash VARCHAR (50) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
